version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-mem
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - ./keycloak:/opt/keycloak/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
